# Generated by Django 3.0.6 on 2020-08-11 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200811_0318'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
