# Generated by Django 3.0.6 on 2020-08-23 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user',
            new_name='writer',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='writer',
        ),
    ]
