# Generated by Django 3.0.6 on 2020-08-24 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_view_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='post',
            new_name='product',
        ),
    ]
